1- D Array

In [8]:
import numpy as np
a = np.array([5, 5, 5, 1])
a

array([5, 5, 5, 1])

In [10]:
type (a)


numpy.ndarray

In [12]:
len(a)

4

In [14]:
a[0]

5

In [16]:
a[0:]

array([5, 5, 5, 1])

2-D Array

In [19]:
# List of the lists
b = np.array([[5, 5, 5], [5, 5, 5], [5, 5, 5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [21]:
type(b)

numpy.ndarray

In [23]:
len(b)

3

In [25]:
b[0]

array([5, 5, 5])

In [27]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [31]:
# import numpy as np
a = np.array([5, 5, 5])
a

array([5, 5, 5])

In [33]:
type(a)

numpy.ndarray

In [35]:
len(a)

3

In [37]:
a[0]

5

In [39]:
a[0:]

array([5, 5, 5])

1-d Array

Array Attributes

Dimensions are called axis



In [5]:
import numpy as np
c = np.array([[5, 5, 5], [5, 5, 5]])
c

array([[5, 5, 5],
       [5, 5, 5]])

In [7]:
import numpy as np 
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
b = np.zeros(2)
b

array([0., 0.])

In [11]:
c = np.ones(3)
c

array([1., 1., 1.])

In [13]:
# Create empty array with 2 elements
d = np.empty(3)
d

array([1., 1., 1.])

How to create an array ?

In [16]:
# With range of the elements
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [18]:
# With specific range of elements 
f = np.arange(2, 20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
# Continure
g = np.arange(2, 20, 2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# Lineraly spaced arrays
h = np.linspace(0,10,num=5) # give use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
# Specific data types in array
i = np.ones(5, dtype = np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [26]:
j = np.ones(3, dtype = np.float64)
j

array([1., 1., 1.])

2-D Arrays

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

How To Create an array?


3-D Array


In [38]:
# Maaking and reshaping 3d array
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

numpy practice session

In [ ]:
# Pip install numpy


In [43]:
# import the library in the j. nootbook
import numpy as np

In [45]:
# Create an array using numpy

In [49]:
food = np.array(["pakoras", "samosas", "raitas"])
food

array(['pakoras', 'samosas', 'raitas'], dtype='<U7')

In [53]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [55]:
type(price)

numpy.ndarray

In [59]:
type(food)

numpy.ndarray

In [61]:
len(price)


3

In [63]:
len(food)

3

In [65]:
price[2]

5

In [67]:
 food[1]

'samosas'

In [69]:
price.mean()

5.0

In [71]:
# Zeros Method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [73]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [75]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [77]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [81]:
# Specific range with specific interval
np.arange(2, 20, 5)

array([ 2,  7, 12, 17])

In [83]:
# Tabel of 5
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [87]:
# line space
np.linspace(0, 100, num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [89]:
# Specifiy your data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [91]:
#specify your datatype float
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array Function

In [98]:
a = np.array([10,12,14,2,4,6,100,320,0.5,10.3])
a
             

array([ 10. ,  12. ,  14. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [100]:
# Sorting the array
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  14. , 100. ,
       320. ])

In [102]:
a.transpose()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  14. , 100. ,
       320. ])

In [104]:
b = np.array([10.2, 32.4])
b

array([10.2, 32.4])

In [106]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  14. , 100. ,
       320. ,  10.2,  32.4])

In [108]:
c.sort()
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,  14. ,
        32.4, 100. , 320. ])

# 2-D Arrays

In [127]:
x = np.array([[1,2,], [5,4,]])
x

array([[1, 2],
       [5, 4]])

In [133]:
y = np.array([[6,7], [7,8]])
y

array([[6, 7],
       [7, 8]])

In [135]:
np.concatenate((x,y), axis=0)


array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [137]:
np.concatenate((x,y), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [147]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 7, 8]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],
               
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]])
a

                

array([[[0, 1, 2, 3],
        [4, 5, 7, 8]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [149]:
# To find the number of dimension
a.ndim

3

In [151]:
b = np.array([[5,6,7],
             [8,9,10],
             [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [153]:
b.ndim

2

In [155]:
a.size

24

In [157]:
a.shape

(3, 2, 4)

In [169]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [171]:
# Reshape
b = a.reshape(3, 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [175]:
# Reshape
np.reshape(a, newshape=(1, 9), order = 'c')



array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [177]:
# convert 1D into 2-D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
a.shape

(9,)

In [181]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [183]:
b.shape

(1, 9)

In [185]:
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [187]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [189]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [191]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [193]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [195]:
a.sum()

45

In [197]:
a.mean()


5.0